apiVersion: apps/v1
kind: Deployment
metadata:
  name: goaccess
  namespace: traefik-system
  labels:
    app: goaccess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goaccess
  template:
    metadata:
      labels:
        app: goaccess
    spec:
      containers:
      - name: goaccess
        image: allinurl/goaccess:latest
        command:
        - /bin/sh
        - -c
        - |
          tail -F /var/log/traefik/access.log | goaccess --config-file /etc/goaccess/goaccess.conf -
        volumeMounts:
        - name: traefik-logs
          mountPath: /var/log/traefik
        - name: config
          mountPath: /etc/goaccess
        - name: db
          mountPath: /root/.goaccess
        ports:
        - containerPort: 7890
          name: http
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: traefik-logs
        persistentVolumeClaim:
          claimName: traefik-logs
      - name: config
        configMap:
          name: goaccess-config
      - name: db
        emptyDir: {}