apiVersion: apps/v1
kind: Deployment
metadata:
  name: goaccess
  namespace: traefik-system
  labels:
    app: goaccess
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goaccess
  template:
    metadata:
      labels:
        app: goaccess
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
          readOnly: true
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 3
      - name: goaccess
        image: allinurl/goaccess:latest
        command:
        - /bin/sh
        - -c
        - |
          # Create report directory if it doesn't exist
          mkdir -p /srv/report

          # Start GoAccess with real-time HTML and WebSocket server
          tail -F /var/log/traefik/access.log | \
          goaccess - \
            --config-file=/etc/goaccess/goaccess.conf \
            --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u"' \
            --date-format='%d/%b/%Y' \
            --time-format='%H:%M:%S' \
            --real-time-html \
            --ws-url=wss://stats.midagedev.com/ws \
            --origin=https://stats.midagedev.com \
            --port=7890 \
            --addr=0.0.0.0 \
            -o /srv/report/index.html
        volumeMounts:
        - name: traefik-logs
          mountPath: /var/log/traefik
        - name: config
          mountPath: /etc/goaccess
        - name: data
          mountPath: /srv/report
        - name: db
          mountPath: /root/.goaccess
        ports:
        - containerPort: 7890
          name: websocket
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: traefik-logs
        persistentVolumeClaim:
          claimName: traefik-logs
      - name: config
        configMap:
          name: goaccess-config
      - name: data
        persistentVolumeClaim:
          claimName: goaccess-data
      - name: db
        emptyDir: {}
      - name: nginx-config
        configMap:
          name: nginx-config