apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goaccess-data
  namespace: goaccess
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goaccess-logs
  namespace: goaccess
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
