apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goaccess-data
  namespace: traefik-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
