apiVersion: v1
kind: ConfigMap
metadata:
  name: goaccess-script
  namespace: traefik-system
data:
  entrypoint.sh: |
    #!/bin/sh

    # Create report directory
    mkdir -p /srv/report

    # Run GoAccess without ws-url parameter
    # Let it generate default WebSocket URL then fix via proxy
    tail -F /var/log/traefik/access.log | \
    goaccess - \
      --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u"' \
      --date-format='%d/%b/%Y' \
      --time-format='%H:%M:%S' \
      --real-time-html \
      --origin=https://stats.midagedev.com \
      --port=7890 \
      --addr=0.0.0.0 \
      -o /srv/report/index.html